### ISSUE TITLE
djs12

### ISSUE THREAD

**Issue by ghost** [DS-Development/delet#250]
Hello. Discord updated to v12 and im wondering if someone in your team could update this? hope to see this updated soon!

**Comment by suvanl** [comment]
hi there,

as stated in https://github.com/DS-Development/delet/pull/248#issuecomment-607287225, due to the fact that delet 2.8.3 will soon be deprecated in favour of delet 3.0.0 (delet<sup>3</sup>), this version of delet won't be updated to Discord.js v12 (and probably won't receive any further updates in general). 

however, delet 3.0.0 (which exists in a new repository) will use Discord.js v12, as well as Node v12 (as this is a minimum requirement for djs12).
