### ISSUE TITLE
Mute handler

### ISSUE THREAD

**Issue by oodvg** [DS-Development/delet#264]
Hello. Its me again with another suggestion
I suggest a Mute handler so if someone tags the server owner without a moderation permlevel, the user gets automuted for 10 mins. The bot dms the user saying "Looks like you tag **Owners name** so I have muted you for 10 mins."
after the 10 mins, auto unmute takes place and removes the Muted role from the user without saying anything in dms.
Please make it so we can setup different ids such as roles and users.
ex, someone with a Super OG role. if someone without a moderation permlevel who tags someone with the role, they also get automuted for 10 mins

**Comment by suvanl** [comment]
Hey, this seems like an interesting suggestion as well, especially for larger servers. 

I think it'd be useful to implement a settings toggle for this (off by default), so that server admins can enable it at their discretion. Allowing different role/user IDs to be used shouldn't be a problem, seeing as a setting for this can be created as well.

Thanks a lot for the suggestion; this will also be considered for delet<sup>3</sup>. 👍

**Comment by oodvg** [comment]
Okay. are you open to more suggestions?

**Comment by suvanl** [comment]
Yeah, of course!
