### ISSUE TITLE
bot-command config

### ISSUE THREAD

**Issue by oodvg** [DS-Development/delet#266]
one more suggestion until i come up with more.

a bot-command config to prevent commands being ran in a general channel. however, permlevel 2 (moderation) can bypass to use moderation commands
example, /set edit botcmds [channel name]
message.channel.send("botcmds successfully edited to [channel name]")
if normal user tries to run a command in a wrong channel, bot replys "commands can only be ran in [#channel name]!" this should prevent commands to be ran into the wrong channel.

**Comment by suvanl** [comment]
This seems handy, though I feel it'd be more suitable if it worked more like an "ignore" or blacklist system, e.g.:
- users (with sufficient perms) can specify which channel(s) the bot should ignore
     - if they want the bot to ignore all channels, they can use an "all" option, and provide an exception*
    - this means users can have multiple channels in their server where bots can be used (because, for example, they might want two such channels rather than one)
- the bot ignores the specified channel(s) completely (probably through some logic in the `message` event)
- commands fail silently, rather than with a reply, as this sort of falls under point 6 on the [list of best practices](https://github.com/meew0/discord-bot-best-practices) for Discord bots

*I've yet to think of a way of doing this, as it could make settings quite messy

Once again, thanks for the suggestion!

**Comment by oodvg** [comment]
Okay. Seems fair. Also quick question. Is there any support server/test server I can help test if you would like, I understand if not :) .

**Comment by suvanl** [comment]
There isn't one at the moment, unfortunately, but I'll let you know if a public test server is created (or the bot's readme will be updated with a link to the public server)
